### ISSUE TITLE
Javadocs do not open from downloaded zip, DMG

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#112]
@yorkpf reported this today. It used to work. Odd.

**Comment by dbenn** [comment]
@yorkpf reported this today. It used to work. Odd.

**Comment by dbenn** [comment]
Download any of the win, mac or bash archives from https://github.com/AAVSO/VStar/releases/tag/2.21.2 

Navigate to `doc/vstar_docs` in the uncompressed VStar archive (under `Extras` folder in Mac DMG, `vstar` dir in bash and win) and open `index.html` in a browser. Selecting any package or class does nothing at all!

This was not always the case and certainly not last time I looked. @yorkpf and I have seen this on the Mac. Can someone else reproduced this on Windows or Linux? (@mdadighat, @mpyat2, @clkotnik, @SaraAAVSO)

**Comment by mpyat2** [comment]
I tried vstar-bash-2.21.2.zip, vstar-win-2.21.2.zip (under Windows)
Yes, I cannot see any doc (see screenshot below)
This is because 'vstar/doc/vstar_docs/org/' directory is EMPTY (in ZIP and
in unzipped bunch)

[image: image.png]

**Comment by dbenn** [comment]
Ah, yes. Quite right! Sorry.

I've just tracked this down. It's an error in the Ant build targets. Need `<include name="vstar_docs/*" />` to become `<include name="vstar_docs/**" />`. Will sort this out.

Thanks!

**Comment by mpyat2** [comment]
By the way, I realized that vstar_docs is completely missing in the Windows
EXE installer ( VStarWinSetup_2.21.2.zip
<https://github.com/AAVSO/VStar/releases/download/2.21.2/VStarWinSetup_2.21.2.zip>).
This is because I've never run 'javadoc' build option.
Now I tried it and rebuilt vstar-win.zip again:
ant javadoc
ant win

'ant javadoc' generates normal vstar_docs directory, all documents are
accessible.
However, 'ant win' makes vstar-win.zip with empty
vstar/doc/vstar_docs/org/.

BTW, Javadoc displays a lot of errors while building documentation.

Cheers,
Max

**Comment by mpyat2** [comment]
Indeed, with this fix, all documents included in the zip!

**Comment by dbenn** [comment]
Yes, ant win, ant bash, ant mac all suffer from the same problem. Thanks for the confirmation. Will fix this and seek review.

**Comment by dbenn** [comment]
[vstar_docs.zip](https://github.com/AAVSO/VStar/files/5861472/vstar_docs.zip)

**Comment by dbenn** [comment]
@mpyat2 I am aware of the Javadoc generation errors/warnings. That's probably a separate issue though. The effects appear to be harmless though (e.g. complaints about "->" in a comment" probably because of embedded HTML confusion).

**Comment by dbenn** [comment]
@mpyat2 suggests making win, bash, mac targets dependent upon javadoc target to ensure it's generated.
