### ISSUE TITLE
VeLa dialog does not show any output

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#127]
![image](https://user-images.githubusercontent.com/44919945/110138598-cf592300-7dda-11eb-8615-9affa575d2f4.png)

No output after [RUN].

**Comment by dbenn** [comment]
Hi @mpyat2, yes it's true. I have relied upon the use of print() here. Given that the main use for that is really in the VeLa dialog, I agree that at least the last expression should be output. If other intermediate expressions are desired to be output, print can still be used. I initially thought of this as like a REPL, but then shied away from that. No very good reason though. I must have made that change between first writing https://github.com/AAVSO/VStar/wiki/VeLa because the dialog under `Running VeLa Code` there shows output. Perhaps that's what led you to this bug? Anyway, I agree with fixing it.

**Comment by dbenn** [comment]
Perhaps the wiki page needs to be updated too (in the section I mentioned above)?

**Comment by mpyat2** [comment]
Thank you, David. Indeed,  I read the old Sourceforge Wiki and tried the example.
