### ISSUE TITLE
Error in invoking Plug in Manager

### ISSUE THREAD

**Issue by orionlee** [AAVSO/VStar#178]
When I clicked Tool > Plug-in Manager, I got the following error:

![image](https://user-images.githubusercontent.com/250644/123370086-d9db2c00-d533-11eb-949c-187ce56fab08.png)
![image](https://user-images.githubusercontent.com/250644/123370103-e3fd2a80-d533-11eb-99f7-fc50a99ab604.png)

Log shown
```
Jun 24, 2021 10:12:42 PM org.aavso.tools.vstar.ui.dialog.MessageBox showErrorDialog
SEVERE: Error reading remote plug-in information.
Jun 24, 2021 10:12:44 PM org.aavso.tools.vstar.ui.dialog.MessageBox showErrorDialog
SEVERE: null
```

Then I opened Preference, and found the plug-in location base URL is:
  https://www.aavso.org/sites/default/files/vstar-plugins/vstar-plugins-2.21.2

When I paste the base URL to a browser window, I got page not found.

I used to be able to access plug-in manager but somehow it no longer works. I haven't used VStar for a while though.

---

Version: 2.21.2
Platform: Windows

**Comment by dbenn** [comment]
Hi @orionlee 

The latest version of VStar is 2.21.3 so the simplest thing would be to switch to that.

See https://www.aavso.org/vstar-2213-released

That version also has enhanced Plugin Manager features (e.g. add/delete all plugins).

The only other option is to install the plugins in 2.21.2 from an uncompressed downloaded zip file. We don't really have the resources to support past versions of VStar though.

Also, I would suggest avoiding WebStart with 2.21.3 at least for now because of a plugins related bug that's being worked on (https://github.com/AAVSO/VStar/issues/175).

The AAVSO compute infrastructure has changed in recent times as I recall, so anything before the latest version may not exist now. @SaraAAVSO could confirm/deny.

David

**Comment by orionlee** [comment]
@denn Thanks for the prompt reply!

With v2.21.3, I still got exactly the same error (both the UI and in the log).
- the specific release I downloaded is: https://github.com/AAVSO/VStar/releases/download/2.21.3/vstar-win-2.21.3.zip
- In Preference, the plug-in location base URL still references a 2.21.2 URL:
`https://www.aavso.org/sites/default/files/vstar-plugins/vstar-plugins-2.21.2`

**Comment by mpyat2** [comment]
Try to press 'Set Defauls' in the Preferences/Plug-ins.
See also https://github.com/AAVSO/VStar/wiki/Installation-Recipes#plug-ins

**Comment by orionlee** [comment]
Press 'Set Defaults' resolves the problem. Thanks!
