### ISSUE TITLE
Labelling each Light Curve

### ISSUE THREAD

**Issue by yorkpf** [AAVSO/VStar#195]
We need a feature, probably in “Properties”, whereby we can change the names (labels) of the individual light curves, as we are able to do already with the title.

This is typically necessary when a light-curve is base-line shifted and the label needs to be changed from something like “ZTF gr” to (say) “ZTF gr+0.2”.  As you know, to achieve this currently requires setting up a filter plus a new series, a disproportionate (and error-prone) amount of work just to achieve something cosmetic.

**Comment by mpyat2** [comment]
Existing alternative way to assign custom labelling: (1) save data as a text file (2) add #defineseries and #filter directives (3) load data via Flexible Text plug-in (see Flexible Text Format plugin doc for details).
Personally, I prefer to work with all data converted to unified text files (via VStar Save... menu command) readable by the Flexible Text Format plugin. After conversion to a text I add appropriate  #NAME, #FIELDS, #DELIM, #DATE, #DEFINESERIES, #FILTER and #MAGSHIFT (if needed) directives so I have a dataset ready to load without additional manual tuning. Sometimes even outliers can be automatically removed with #VELAFILTER directive. See Flexible Text Format doc for details.

**Comment by yorkpf** [comment]
Hi Maksym

I did know about this alternative approach, but normally one doesn’t know the required mag-shift values at the point of “editing” the data file.

One needs to load up the data into VStar and turn it into a light curve and then view that (and all of the other) light curves together to decide which curve/s requires shifting and by how much. It seems inefficient to then go back and re-do some of the data files just to correctly label a curve.

Another thing I notice is that (looking at the document “Flexible Text File Plugin”), MAGSHIFT appears to be the only directive that is not dealing with the data file as presented - it describes something that happens to the data later on, if at all) and does not seem intrinsic to the business of conditioning or shaping the supplied data. I offer this as another reason why the re-labelling should be a feature of Properties - it is essentially just a matter of presentation.

Paul

PS. What about the “philosophy” of the whole plug-in approach? Would it make more sense to massage every file (no matter the source) into “flexible text format”” and use only the plug-in “New Star from Flexible Text Format File …”?

**Comment by dbenn** [comment]
@yorkpf to clarify, are you asking for a series name to be changed, e.g. after a baseline shift operation? So, if you mag shift the V series, you want to be able to rename that series as V+0.2, for example?

**Comment by dbenn** [comment]
@yorkpf re:
> Would it make more sense to massage every file (no matter the source) into “flexible text format”
an observation sink plugin could achieve conversion of observations to such a format, potentially useful for multiple data source loads during a session.

**Comment by yorkpf** [comment]
That’s exactly right, David.

**Comment by yorkpf** [comment]
HI David

You asked: Would it make more sense to massage every file (no matter the source) into “flexible text format”?”

I have thought about this approach, more than once. However, if you had a one-size-fits-all program to take as an input “any” observation file from any source, it had better be interactive and able to offer a range of choices: about how to find and throw away certain classes of obs (bad cat-flag etc), how to add certain # commands at the front etc etc … It would require a fair bit of work. And how would that sit with what seems to be the current design approach: a single version of VStar with multiple plug-ins - one for each type of file?

I think this is a design consideration upon which, given my lack of knowledge of the VStar code, I don’t think I should express an opinion, other to suggest that we need to clearly classify the types of pre-processing that can be done a) prior to analysis; b) during analysis; and (c) after analysis (presentation). There may be other categories.

Note however: This approach would still not solve the problem of re-labelling a series curve, because you don’t know the quantum of the shift until the curves have actually  been plotted.

Paul

**Comment by dbenn** [comment]
Re: your last point @yorkpf, there's overlap with #194 I think, as a way to address this. Do you agree?

**Comment by dbenn** [comment]
Regarding just renaming @yorkpf, it may be that we want to create a new user-defined series for this purpose, retaining the old, as a selectable series. I will look into this.

**Comment by yorkpf** [comment]
Definitely an overlap. Which is why I am suggesting we try to get a bit more clarity on the process that VStar encodes. Maybe we need to have a live session on this?

Paul

**Comment by dbenn** [comment]
Sometimes I have to resist analysis paralysis and do something. :)

I have added a `Create Series` item to the `View` menu on a branch. It works the same way as the button in the previous filters dialog but allows any existing series (except a user defined series, i.e. via `Create Series` button or menu item).

A few issues/questions arise, some already raised here or elsewhere:
- Is _copy_ existing series what is wanted, or _rename_ existing series? I favour the former because mutating an existing series has implications for preferences, underlying series type "metadata"/code.
- Observations are not deep copied so side effects from future operations are possible. See #51 and #49.
- User created observation series do not currently show up in the observation list pane, so cannot be saved to a file or searched for example.

**Comment by yorkpf** [comment]
David

I am inclined to think the former also …

Moreover, I am not sure that the last 2 dot points matter much, but:

What do you mean by "deep copied”?
Paul

**Comment by dbenn** [comment]
The last 2 dots points are essentially
* a copied observation series should not be modified if the source observation series is modified;
* since you may want to save a copied observation series (e.g. V+2), it should be visible in the observation list pane if selected in the Plot Control dialog.

Shallow copy of `a` to `b` means that `b` is just a pointer to `a` (has a reference to `a`).
Deep copy of `a` to `b` means that `b` is a new object whose future history is divorced from `a`'s.

Deep vs shallow copy relates to the first dot point.

**Comment by yorkpf** [comment]
Thanks David.

That’s pretty clear. So what I envisage for relabelling a series is a “copy” …

So, just looking back over all of our exchanges over the last 6 months, I don’t think we still need to meet … the issues seem to be addressed.

Cheers
Paul
