### ISSUE TITLE
to keep "Light curve control" settings in "Show" group after loading a new portion of data.

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#244]
It would be convenient if "Light curve control" settings in "Show" group, such as "Error bars?", "Cross-hair?", "Invert range?", "Invert Series Order?" were kept while loading new data.

**Comment by dbenn** [comment]
I assume you're thinking this should be true for any data load, not just additive loads for the same target @mpyat2?

**Comment by dbenn** [comment]
Currently, the initial values for these plot control dialog checkboxes are taken from the plot pane state, set in the dialog's constructor:
~~~
		// Get initial checkbox values.
		showErrorBars = plotPane.getRenderer().getDrawYError();

		showCrossHairs = plotPane.getChartPanel().getChart().getXYPlot()
				.isDomainCrosshairVisible(); // ask for domain or range value

		invertRange = plotPane.getChartPanel().getChart().getXYPlot()
				.getRangeAxis().isInverted();
		
		invertSeriesOrder = plotPane.getChartPanel().getChart().getXYPlot()
				.getSeriesRenderingOrder().equals(SeriesRenderingOrder.REVERSE);

		joinMeans = obsModel.getMeansSeriesNum() != ObservationAndMeanPlotModel.NO_SERIES ?   
                                 plotPane.getRenderer().getSeriesLinesVisible(obsModel.getMeansSeriesNum()) : false;
~~~
This explains why they are reset when a dataset is loaded. Another approach would be to persist these values across dataset loads, e.g. by storing them in the DocumentManager or Mediator or as static members of the dialog class. Then, when the dialog loads, rather than using the `plotPane` as the source of checkbox state, instead, the checkbox state would set the `plotPane` state.

**Comment by dbenn** [comment]
@mpyat2 I believe I've made the changes you need here; tests look OK so far; please feel free to give it a try; I'll create a pull request for you to look at when the mood takes you...
