### ISSUE TITLE
Simple filter fails with more than one Phase condition

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#319]
Simple filter Phase > -0.1 works, Phase < 0.1 also works, however, when I try both conditions, a warning occurs (No observations).
![image](https://user-images.githubusercontent.com/44919945/211533410-934f2272-f59b-449c-ba25-356c88fab952.png)
![image](https://user-images.githubusercontent.com/44919945/211533433-6ab4c331-758f-44d6-9194-1ff81a0e7718.png)
![image](https://user-images.githubusercontent.com/44919945/211533462-3675fdfd-98b9-4816-8b69-54e7f05d89fd.png)
![image](https://user-images.githubusercontent.com/44919945/211533479-62d175e9-c604-41d8-bc96-afb2e5efb123.png)

**Comment by dbenn** [comment]
Yes, thanks @mpyat2. I think I know what's going on here. I'll reply with details tomorrow (after midnight and I need to get up early).

**Comment by dbenn** [comment]
Oh, so that's weird. The equivalent VeLa filter works and the simple filter description reported in the Previous Filters dialog for that simple filter is identical to that VeLa filter!

**Comment by dbenn** [comment]
Okay, so what's happening is that `PhaseFieldMatcher` is actively changing values less than zero into standard phase values by adding one. This also requires the relational operators to be changed (e.g. `>` to `<=`) if a `<` or `>` is involved but the code was not doing this.

There was no unit test for `PhaseFieldMatcher`, so not surprising this was missed.

So, either the relational operator needs to be changed or only positive values are allowed. If the latter, to express a filter such as `phase < 0.1 or phase > 0.9` would not be possible with the simple filter dialog since disjunction is not supported. A VeLa filter would have to be used.

Another approach would be to allow `standardphase` and `previouscyclephase` explicitly both here and in for VeLa filters (see #320). I'm starting to be inclined to do this.

**Comment by mpyat2** [comment]
Hi @dbenn , explicit standardphase and previouscyclephase is a good idea

**Comment by dbenn** [comment]
This works now: `previouscyclephase > -0.1 or standardphase < 0.1`

**Comment by dbenn** [comment]
I'm considering #319 and #320 together here, hence the VeLa example above. I think that any simple filter and VeLa filter changes made re: phase can just happen on #320's branch.

**Comment by dbenn** [comment]
One thing to keep in mind @mpyat2 is that since `previouscyclephase = 1 - standardphase`, a filter that selects `standardphase = N` will also correspond to `1 - N` (previouscyclephase). These in fact correspond to the same observations.

A simple way to see this is with this VeLa filter: `standardphase > 0.69 and standardphase < 0.71`.

Note also that to get discrete subsets of phase, disjunction will have to be used, e.g. try this:
~~~
(standardphase > 0.69 and standardphase < 0.71) or
(previouscyclephase > -0.81 and previouscyclephase < -0.79)
~~~
This is **_not possible_** with a Simple (dialog based) Filter, only a VeLa (or custom) filter, since Simple Filters are implicitly conjunctive.
