### ISSUE TITLE
VeLa filter on Phase gives strange result

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#320]
Try the following VeLa filter: Phase >-0.1. ALL points will be selected.

![image](https://user-images.githubusercontent.com/44919945/211533926-8e70d7ea-b0a0-4930-9784-4ee10ce91855.png)

**Comment by dbenn** [comment]
Hi @mpyat2. This seemingly odd result is due to the fact that every observation in a phase plot has:
- standard phase (or just phase), with range 0 to 1
- previous cycle phase, with range -1 to 0
  - in particular, previous cycle phase is standard phase - 1

In VeLa, when you ask for `phase`, you're getting standard phase.

If your filter is changed to `phase > 0.9`, the result you seek will be achieved.

Some possibilities:
- document that 0 < `phase` < 1?
- split `phase` into standard and previous cycle phase?

Previous cycle phase is a convenience to allow phase plots to show a representative phased light curve by placing two identical phase plots together. It's a visual aid more than anything.

We could try to combine standard and previous cycle into `phase` for filtering purposes, but that would require some work.

Make sense?

**Comment by mpyat2** [comment]
Well, I think it's enough to document that phase > 0 and phase < 1, at least for now.
So, if anyone wants to filter for a phase in [-0.1 .. 0.1], she/he can write:
```
phase <0.1 or phase >0.9
```
![image](https://user-images.githubusercontent.com/44919945/212286814-aacacbda-4fb3-4b73-afaf-594e750d00a1.png)

**Comment by dbenn** [comment]
@mpyat2, I've changed the user manual text like so (with better use of bold/italic and font change)

> Note that for filters (see Filtering Observations section) where the value of the observation's phase is sought, the range of phase values from 0 to 1 on the phase plot is the so-called standard phase or simply, the phase. The so-called previous cycle phase value is defined as:
>
>   1 - standard phase
> 
> and occupies the range from -1 to 0 on the phase plot. Selecting an observation via a filter with a particular phase, will also select the observation with the corresponding previous cycle phase, since this corresponds to the same observation.
> 
> A Simple Filter (View → Simple Filter dialog) can express the equivalent of this VeLa filter (View → VeLa Filter):
> 
>   phase > 0.69 and phase < 0.71
> 
> but not this one:
> 
>   (standardphase > 0.69 and standardphase < 0.71) or
>   (previouscyclephase > -0.81 and previouscyclephase < -0.79)
> 
> Simple Filters do not allow disjunction (“or”). Only conjunction (and) between filter expression terms.
> 
> So, Simple Filters allow only phase to be specified (range 0 to 1), while VeLa filter expressions can contain the variables phase, standardphase and/or previouscyclephase.

**Comment by mpyat2** [comment]
@dbenn , sounds good!
