### ISSUE TITLE
"Magnitude and Time Shifter" plug-in counterintuitive behaviour

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#452]
I'm not sure if it is a bug or a feature. 
1) Open observations in several different filters
2) Tools->Magnitude and Time Shifter: you will see the "Select a series" dialog
3) Click the "Deselect All" button. Not only will the checkboxes be cleared, but all the series will become invisible.
4) Click the "Select All" button. The checkboxes will be checked; all series will become visible.

On the other hand, clicking on checkboxes does not change the visibility of the series.

I'm also not sure the "Means" series makes sense here.

**Comment by dbenn** [comment]
Thanks for reporting this @mpyat2. I understand what's causing the problem and will fix ASAP. I had generalised the dialog's components but missed a couple of checks.

It's a good question re: whether Means or other synthetic series, e.g. model and residual datapoints, make sense in the context of `ObservationTransformation` plugins. Initially I did not want to be prescriptive. I'm happy to remove Means, model, residuals, if you agree. Filtered series probably makes sense still since you can create series from such a series. Or perhaps only user-defined series created from a filter series should be included.

Let me know what you think.

**Comment by mpyat2** [comment]
Hi @dbenn 
I agree with your approach. I think the filtered series can be included.

**Comment by dbenn** [comment]
#453 created
